#!/bin/bash
sleep 5
# this is for a particular installation
# you'll need to make your own changes
TODAYS_DATE=$(date +%Y-%m-%d_%H_%M_%S)
source /home/pi/sandbox/weather-env/bin/activate
python /home/pi/sandbox/weatherBalloon/weatherBalloon.py &> /home/pi/sandbox/weatherBalloon.$TODAYS_DATE.out
